version: 1.3.0.{build}
image: Visual Studio 2019
init:
- cmd: choco install msbuild.communitytasks
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer

environment:
  ReleaseNumber: 1.3.0
  InnoSetupPath: "C:/Program Files (x86)/Inno Setup 6"

before_build:
- dotnet restore src/1Script.sln
build_script:
- cmd: |-
    msbuild src/1Script.sln /t:restore
    dotnet publish src\OneScriptDocumenter\OneScriptDocumenter.csproj -o doctool
    set OneScriptDocumenter="doctool\OneScriptDocumenter.exe"
    msbuild Build.csproj /t:CleanAll;PrepareDistributionContent;xUnitTest;CreateDistributions /p:ReleaseNumber=1.3.0 /p:InnoSetupPath=%InnoSetupPath% /p:OneScriptDocumenter=%OneScriptDocumenter%
test: off
artifacts:
- path: built/OneScript-*.exe
- path: built/OneScript-*.zip
- path: built/mddoc-*.zip
- path: tests/tests.xml

#test_script:
#- cmd: >-
#    opm install -l asserts
#    opm install -l logos
#    echo "lib.system=C:/Program Files (x86)/OneScript/lib" > src/oscript/bin/x86/Release/net452/oscript.cfg
#- cmd: appveyor-runtests.cmd
#after_build:
#- 7z a oscript.zip %APPVEYOR_BUILD_FOLDER%/src/oscript/bin/x86/Release/net452/*.dll
#- 7z a oscript.zip %APPVEYOR_BUILD_FOLDER%/src/oscript/bin/x86/Release/net452/*.exe
#artifacts:
#- path: oscript.zip
#  name: oscript.zip
