name: Build and Deploy

on: [push]

jobs:
  build:
    env:
      ReleaseNumber: 1.0.3 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: msbuild Build.csproj /t:CleanAll;CreateDistributions /p:ReleaseNumber=%ReleaseNumber%
